@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}/api
@contentType = application/json
@createdAt = {{$datetime iso8601}}


### 注册
POST {{host}}/user/register 
content-type: {{contentType}}

{
    "username": "1",
    "password": "1",
    "email": "1@qq.com"
}
### 登录
POST {{host}}/user/login 
content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQwOWFhZjkyZTdiMjcyZTI5NWRmMTYiLCJpYXQiOjE2MzE2Mjg1NTZ9.SElJx02iB_jfmCvOedbMa3GwlQPMt26oufSVt8tmw54

{

    "password": "1",
    "email": "1@qq.com"
}
### 获取用户信息
POST {{host}}/user/ 
content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQwOWFhZjkyZTdiMjcyZTI5NWRmMTYiLCJpYXQiOjE2MzE2Mjg1NTZ9.SElJx02iB_jfmCvOedbMa3GwlQPMt26oufSVt8tmw54

{

}

### 创建文章
POST {{host}}/article 
content-type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQwOWFhZjkyZTdiMjcyZTI5NWRmMTYiLCJpYXQiOjE2MzE2Mjg1NTZ9.SElJx02iB_jfmCvOedbMa3GwlQPMt26oufSVt8tmw54

{
  "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
}